- setup.py
`brew reinstall gcc --without-multilib` should be run to install gcc with OpenMP support
> Added Note

- gprMax/input_cmd_funcs.py
- user_models/cylinder_2D_py.in
This is not complete, there are still missing commands and not all of the functions return a Coordinate object. But I just wanted to know if this looks like a sensible approach? 
I attached a cylinder_2D_py.in, which is definitely more verbose than the existing example, but I prefer the explicitness of the python syntax.
Something should also be done to link the documentation to the input.html, I have just copy pasted most of the doc-strings from there...
> added some additional input_cmd_funcs and named tuple Coordinate.

- gprMax/input_cmd_funcs.py
the unpacking was unnecesary anyway, ref #54
> fixing SyntaxError in input_cmd_funcs.py

- gprMax/input_cmds_multiuse.py
- gprMax/model_build_run.py
Snapshot is available with GPU. And bugfix for simulation with GPU when no rx exists.
> Bugfix for when no rx commands and using GPU

- docs/source/input.rst
- gprMax/grid.py
- gprMax/input_cmds_file.py
- gprMax/input_cmds_singleuse.py
- gprMax/model_build_run.py
allow user to specify the directory of output files other than the directory of the input files.
> add a input file command #output_dir 

- README.rst
Resolved the errors in README.rst which the official py server was throwing during parsing.
> README.RST errors resolved

- gprMax/model_build_run.py
Updated `solve_gpu` function description to describe `memsolve` return along with `tsolve`.
> Updated `solve_gpu` function description.

- gprMax/gprMax.py
- gprMax/grid.py
- gprMax/model_build_run.py
- gprMax/opencl_kernels/store_outputs.cl
- gprMax/opencl_kernels/update_fields.cl
- gprMax/opencl_kernels/update_source.cl
- gprMax/opencl_solver.py
- gprMax/receivers.py
- gprMax/sources.py
- user_models/my_model.in
- Written PyOpenCl class which will take care of selecting platforms and devices, initializing contexts and queues and also primary solver. 
- Written kernel for basic updates of E and H fields, output storing and source updates.
- Issues with building with Nvidia platforms.
- Although building, there is no correct output.
> opencl feature addition code-base

- gprMax/grid.py
- gprMax/opencl_el_kernels/common.cl
- gprMax/opencl_el_kernels/update_e_dispersive_A.cl
- gprMax/opencl_el_kernels/update_e_dispersive_B.cl
- gprMax/opencl_kernels/update_fields.cl
- gprMax/opencl_solver.py
- Added material property of dispersive materials.
- Traditional method of kernel built works correctly.
- Elementwise kernel building has some issues (not working).
> add property of dispersive material

- gprMax/grid.py
- gprMax/opencl_solver.py
- gprMax/pml.py
Features Added
- Time Profiling for the opencl solver
- Memory Profiling for the solver (there are some overhead memories used by cards, like Nvidia was using 42MB memory over the estimated memory of declared PyOpenCl arrays and so on)
- Added checks for constant memory variables
> added time and memory profiling

- docs/source/opencl.rst
- gprMax/opencl_solver.py
- Docs are updated at `docs/source/opencl.rst`
- Regular documentations can be found [here](https://spacevstab.github.io)
> Docs and Comments added

- gprMax/cmds_geometry/add_grass.py
- gprMax/cmds_geometry/add_surface_roughness.py
- gprMax/cmds_geometry/fractal_box.py
- gprMax/cmds_multiuse.py
- gprMax/config.py
- gprMax/contexts.py
- gprMax/gprMax.py
- gprMax/grid.py
- gprMax/hash_cmds_file.py
- gprMax/updates.py
- testing/benchmarking/bench_simple.py
- toolboxes/AntennaPatterns/plot_fields.py
- toolboxes/DebyeFit/Debye_Fit.py
- toolboxes/DebyeFit/optimization.py
- toolboxes/Plotting/plot_Ascan.py
- toolboxes/Plotting/plot_source_wave.py
- toolboxes/STLtoVoxel/perimeter.py
- toolboxes/STLtoVoxel/slice.py
I found that in many places the code can be updated to make it more readable and clean. So, I went through those files and changed some of their code to make them better.
Refactoring of some code to make it better.
> Refactoring of some code to make it more readable and clean.

- gprMax/cmds_geometry/add_surface_roughness.py
- gprMax/cuda_opencl/knl_fields_updates.py
Issues occured while running:
- models with #add_surface_roughness.
- models with #add_dispersion_debye on GPU (on CPU works fine!)
> Small fixes on add_surface_roughness.py and knl_fields_updates.py

- gprMax/cmds_geometry/add_grass.py
- gprMax/cmds_geometry/add_surface_roughness.py
- gprMax/cmds_geometry/add_surface_water.py
- gprMax/cmds_geometry/box.py
- gprMax/cmds_geometry/cone.py
- gprMax/cmds_geometry/cylinder.py
- gprMax/cmds_geometry/cylindrical_sector.py
- gprMax/cmds_geometry/edge.py
- gprMax/cmds_geometry/ellipsoid.py
- gprMax/cmds_geometry/fractal_box.py
- gprMax/cmds_geometry/fractal_box_builder.py
- gprMax/cmds_geometry/geometry_objects_read.py
- gprMax/cmds_geometry/plate.py
- gprMax/cmds_geometry/sphere.py
- gprMax/cmds_geometry/triangle.py
- gprMax/cmds_multiuse.py
- gprMax/cmds_singleuse.py
- gprMax/config.py
- gprMax/contexts.py
- gprMax/grid.py
- gprMax/hash_cmds_file.py
- gprMax/hash_cmds_singleuse.py
- gprMax/materials.py
- gprMax/snapshots.py
- gprMax/user_inputs.py
- testing/test_models.py
- toolboxes/Plotting/plot_source_wave.py
- toolboxes/Utilities/convert_png2h5.py
At many places even though f-strings are being used, un-necessary concatenations are present, I tried to remove most of them. Also refactored few functions to decrease the code-length and increase readability. 
Refactoring/cleaning of code to make it better.
> Removed un-necessary string concatenations and Refactored few functions.

- .github/ISSUE_TEMPLATE/bug_report.yaml
- .github/ISSUE_TEMPLATE/config.yaml
- .github/ISSUE_TEMPLATE/feature_request.yaml
- CONTRIBUTING.md
- CONTRIBUTING_GUIDE.md
Added a basic contribution guide for gprMax. It is good to have such a file as it serves as a guide for individuals looking to participate and contribute effectively to the project.
> Added a Contribution guide.

- .pre-commit-config.yaml
- gprMax.toml
Updated the `gprMax.toml` file to follow formatting rules according to the `.pre-commit.config.yaml` file, also updated the pre-commit-hooks to latest version.
> Updated the `gprMax.toml` file.

- .github/PULL_REQUEST_TEMPLATE.md
Updated [`pull_request_template.md`](https://github.com/gprMax/gprMax/blob/master/.github/PULL_REQUEST_TEMPLATE.md) file to make it better, corrected grammar mistakes, and also removed un-necessary options in the checklist.
> Updated `pull_request_template.md` file to make it better.

- .pre-commit-config.yaml
Updated `pre-commit hooks` version and checked all the files accordingly.
Closes #
> Updated `pre-commit hooks` version and checked all the files accordingly.

- README.rst
I have noticed one grammatical enhancement in **README** inside section "**Getting Started**"
"**gprMax  is open source**"  should be "**gprMax  is an open source**"
Screenshot-
> Update README.rst - one enhancement

- CODE_OF_CONDUCT.md
Fixed #396
Added CODE_OF_CONDUCT to the Repo.
Importance of  CODE_OF_CONDUCT-  We propose adding a comprehensive Code of Conduct to our repository to ensure a safe, respectful, and inclusive environment for all contributors and users. This code will 
serve as a guideline for behavior, promoting diversity, reducing conflicts, 
and attracting a wider range of perspectives.
@craig-warren  kindly review it and merged the PR. Thank You!
> Fix: Created CODE_OF_CONDUCT.md

- README.rst
Corrected typos and grammar issues, changes were made to enhance the clarity and correctness of the instructions.
kindly review my PR. @craig-warren 
Closes #
> Correct typos in README.rst

- .pre-commit-config.yaml
- gprMax/fractals.py
Updated black formatter version and modified files according to it.
Closes #
> Updated `black` formatter version and modified files according to it.

- README.rst
Closes #397 
- [] The title of my pull request is a short description of my changes.
> Adding contributor url in readme.rst

- gprMax/fractals/fractal_volume.py
The previous approach to generating random numbers for an MPIFractalVolume involved iterating over every cell in the volume and checking if it was inside the local fractal volume. This is very slow (much worse than the serial code), as for every cell a new numpy array is created, a conditional (if statement) is executed, and  `rng.standard_normal()` is called, all within a standard Python for loop.
Instead, the new approach calculates the number of random numbers that need to be generated at each step, removing the need for the conditional check and allowing multiple random numbers to be generated with a single call to `rng.standard_normal()`.
The fractal volume and fractal surface ReFrame tests all pass on ARCHER2.
| Implementation | Time in `generate_fractal_volume()` | Percentage of …
> Improve MPI fractal volume generation performance
